name: bisnisku
version: 1.0.0
publish_to: none
description: A POS App for small coffee shop.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  google_fonts: ^6.2.1
  sqflite: ^2.3.3+1
  floor: ^1.5.0
  currency_text_input_formatter: ^2.2.3
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  get_it: ^8.0.0
  shimmer: ^3.0.0

dev_dependencies: 
  build_runner: ^2.4.11
  floor_generator: ^1.5.0
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

